// Code generated by mockery v2.12.2. DO NOT EDIT.

package user

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// Create provides a mock function with given fields: model
func (_m *MockService) Create(model Model) (uint, error) {
	ret := _m.Called(model)

	var r0 uint
	if rf, ok := ret.Get(0).(func(Model) uint); ok {
		r0 = rf(model)
	} else {
		r0 = ret.Get(0).(uint)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(Model) error); ok {
		r1 = rf(model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *MockService) Get(id uint) (*Model, error) {
	ret := _m.Called(id)

	var r0 *Model
	if rf, ok := ret.Get(0).(func(uint) *Model); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Model)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockService(t testing.TB) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
